#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "EEK_JJS_Thing_1"
  https://create.arduino.cc/cloud/things/5ec04f9c-1d7c-4f9d-b0c6-0735617421dd 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temp;
  bool blueLED;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "DHT.h"
#include "thingProperties.h"
#define BLUE 25
#define TOP_RIGHT 34
#define DHT11Pin 19
#define DHTType DHT11

long tempUpdatedTime = 0;

DHT HT(DHT11Pin, DHTType);
// temp from cloud variable

void setup() {
  HT.begin();
  pinMode(BLUE, OUTPUT);
  pinMode(TOP_RIGHT, INPUT);
  digitalWrite(BLUE, LOW);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  if (digitalRead(TOP_RIGHT)) {
    digitalWrite(BLUE, !digitalRead(BLUE));
    delay(1000);
    blueLED = digitalRead(BLUE);
  }
  if (millis() - tempUpdatedTime > 2000) {
    tempUpdatedTime = millis();
    temp = HT.readTemperature(true);
    Serial.print("Temperature: ");
    Serial.print(temp);
    Serial.println(" °F");
  }
}

/*
  Since BlueLED is READ_WRITE variable, onBlueLEDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlueLEDChange() {
  // Add your code here to act upon BlueLED change
  blueLED = !digitalRead(BLUE);
  digitalWrite(BLUE, blueLED);
  Serial.println("Cloud: Blue LED Status Change");
}
